config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :contacts, only: [:new, :create]
  get 'welcome/index' #define the routes
  root 'welcome#index' #setting the 'welcome' controller index action to the root of application
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,	:validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form",
      :to => "tio.sebastian@outlook.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    slug.nil? || title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :new
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	
	def index
		@posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 7)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Hellz yeah, Your article was successfully saved!"
		else
			render 'new', notice: "Oh no, I was unable to save your post. This must be the work of an enemy stand!"
		end
	end

	def show
	end	
	
	def edit
	end	

	def update
		if @post.update post_params
			redirect_to @post, notice: "Huzzah! Your article was successfully saved!"
		else
			render 'edit'
		end
	end	

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

class HTML < Redcarpet::Render::HTML
	include Redcarpet::Render::SmartyPants
	include Rouge::Plugins::Redcarpet
end

	def markdown(text)
		render_options = {
		  filter_html:     true,
		  hard_wrap:       true,
		  link_attributes: { rel: 'nofollow' }
		}

		renderer = HTML.new(render_options)

		extensions = {
		  autolink:            true,
		  lax_spacing:         true,
		  no_intra_emphasis:   true,
		  strikethrough:       true,
		  space_after_headers: true,
		  fenced_code_blocks:  true,
		  superscript:         true,
		  underline:           true,
		  highlight:           true,
		  footnotes:           true,
		  quote:               true,
		  tables:              true

		}
		Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe

	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page-title">Say Hello!</h1>
<div class="skinny-wrapper wrapper-padding">
	<h1>Thank you for your message!</h1>
	<p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page-title">Say Hello!</h1>
	
<div class="skinny-wrapper wrapper-padding">
	<%= form_for @contact do |f| %>
		<%= f.label :name %><br/>
		<%= f.text_field :name, required: true %>

		<br/>

		<%= f.label :email %><br/>
		<%= f.email_field :email, required: true %>

		<br/>

		<%= f.label :message %><br/>
		<%= f.text_area :message, as: :text %>

		<br/>

		<div class="hidden">
			<%= f.label :nickname %><br/>
			<%= f.text_field :nickname, hint: 'leave this field blank' %>
		</div>

		<%= f.submit 'Send Message', class: "button" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title>Tio Sebastian - Fresh Graduate</title>
		<link href="//fonts.googleapis.com/css?family=Raleway:400,400i,700" rel="stylesheet">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<!-- <script src="js/main.js"></script> -->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<header id="main-navigation" class="clearfix">
		<%= link_to "Tio Sebastian", root_path, class: "name" %>
		<a href="#" class="menu"><i class="fa fa-bars"></i></a>
		<nav id="main-nav">
			<%= link_to "Articles", posts_path %>
			<a href="#">Projects</a>
			<%= link_to "Contact", contacts_path %>
		</nav>
	</header>

    <%= yield %>

	<footer id="main-footer">
		<p class="copyright"> &copy;2017 Tio Sebastian</p>
		<nav>
			<a href="https://twitter.com/"><i class="fa fa-twitter" target="_blank" aria-hidden="true"></i></a>
			<a href="https://codepen.io/tiosebastian/" target="_blank"><i class="fa fa-codepen" aria-hidden="true"></i></a>
			<a href="https://linkedin.com/in/tio-sebastian-a50748113/" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
		</nav>
	</footer>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

var disqus_config = function () {
this.page.url = '<%= url_for(post_url(@post)) %>'; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>';
this.page.title = '<%= @post.title %>';
};
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://tio-sebastian.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		<% end %>

		<%= f.label :title %><br>
		<%= f.text_field :title %>

		<br>
		<br>

		<%= f.label :content, "write your article here" %><br>
		<%= f.text_area :content %>

		<br>
		<br>

		<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="page-title">Stuff I've Written</h1>

	<div id="posts-wrapper" class="skinny-wrapper">
		<% @posts.each do |post| %>
			<div class="post">
				<p class="date"><%= post.created_at.strftime('%B %d, %Y') %></p>
				<h2><a href="#"><%= link_to post.title, post %></a></h2>
				<hr>
			</div>
		<% end %>
	</div>

	<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post-show-content" class="skinny-wrapper wrapper-padding">
	<header>
		<p class="date"><%= @post.created_at.strftime('%B %d, %Y') %></p>
		<h1><%= @post.title %></h1>
		<hr>
	</header>

	<div id="content">
		<%= markdown @post.content %>
	</div>

	<hr>

	<div id="share-box">
		<p>Share "<%= @post.title %>"</p>
		<!-- Twitter -->
		<%= render_shareable :buttons=> ['twitter', 'facebook', 'google_plus'] ,:title=> @post.title + " - " %>
	</div>

	<hr>

	<%= render 'disqus' %>

</div>

<%= link_to "Edit", edit_post_path(@post) %>
<!-- <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %> -->

app/views/welcome/index.html.erb
<div class="wrapper wrapper-padding clearfix">
	<div class="col-1 about homepage-content">
	<h2>About</h2>
	<hr>
	<p>Ramps leggings before they sold out fashion <a href="#">axe.</a></p>
	<p>echo park kombucha unicorn whatever trust fund taxidermy meggings post-ironic hella ethical everyday carry.</p>
	<p>echo park kombucha unicorn whatever trust fund taxidermy meggings post-ironic hella ethical everyday carry. <a href="#">YOLO</a> gastropub master cleanse, next level locavore fingerstache heirloom retro literally distillery wolf blog tote bag williamsburg.</p>

	</div>
	<div class="col-2 homepage-content">
		<h2>Stuff I've Built</h2>
		<hr>
		<h3><a href="#">Sartorial</a></h3>
		<p class="date">Apr 12, 2012</p>
		<h3><a href="#">YOLO</a></h3>
		<p class="date">Feb 15, 2013</p>
		<h3><a href="#">Sartorial</a></h3>
		<p class="date">Jan 1, 2014</p>
	</div>
	<div class="col-3 homepage-content">
		<h2>Stuff I've Written</h2>
		<hr>

		<% @posts.each do |post| %>
		<h3><a href="#"><%= link_to post.title, post %></a></h3>
		<p class="date"><%= post.created_at.strftime("%b %d, %Y") %></p>
		<% end %>
	</div>
</div>